# Generated by Django 5.0.2 on 2024-06-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourRadar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coverPic',
            field=models.ImageField(default='', upload_to='Images/CP'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profilePic',
            field=models.ImageField(default='', upload_to='Images/PP'),
        ),
    ]
