# Generated by Django 5.0.2 on 2024-06-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourRadar', '0003_profile_country_profile_type_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='langauges',
            field=models.CharField(default='', max_length=256),
        ),
    ]
