# Generated by Django 5.0.2 on 2024-06-07 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourRadar', '0004_profile_langauges'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='langauges',
            new_name='languages',
        ),
    ]
